####### Base Config #######
  baseURL = "https://im.youronly.one/snoworld/"             # .Site.BaseURL
  title = "Snoworld ❄️"                                        # .Site.Title; IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  copyright = ""                                            # .Site.Copyright; leave empty and uncommented to override theme default; we are using our own footer
  timeZone = "Etc/UTC"


####### Site settings #######
  paginate = 7
  #paginatePath = "page"                                     # https://example.com/page/2
  rssLimit = 20
  summaryLength = 100                                       # default: 70

  #### Other settings ####
    disqusShortname = "youronlyone"                         # .Site.DisqusShortname
    #googleAnalytics = ""                                    # .Site.GoogleAnalytics


####### Backend settings #######
  canonifyURLs = true                                       # true for our use-case
  #disableAliases = true                                     # use this if we want to use server redirects
  enableEmoji = false                                       # format :smile:.
  enableGitInfo = false
  relativeURLs = false                                      # false for our use-case; make all relative URLs relative to content root
  refLinksNotFoundURL = "https://im.youronly.one/snoworld/"

  ## Dev settings ##
    publishDir = "public"
    enableMissingTranslationPlaceholders = true
    timeout = "30s"

  ## Other settings ##
    disableKinds = ["robotsTXT"]

#### LANG stuff ####
  defaultContentLanguage = "en-ph"
  defaultContentLanguageInSubdir = false
  hasCJKLanguage = true
  languageCode = "en-PH"

  ## Theme settings ##
    pluralizeListTitles = false
  ## Theme settings ##


#######  #######  #######  #######  #######  #######  #######  #######
