# See: https://gohugo.io/getting-started/configuration/

####### BASE CONFIG #######
  baseURL = "https://im.youronly.one/snoworld/"                                              # .Site.BaseURL
  title = "Snoworld ❄️"                                                # .Site.Title; IMPT for Schema.org; OpenGraph; Twitter Cards; RDFa, Microdata, JSON-LD
  copyright = ""                                            # .Site.Copyright; leave empty to override theme
  timeZone = "Etc/UTC"


####### FRONTEND #######
  paginate = 7                                             # default: 10
  rssLimit = 25                                             # default: -1
  summaryLength = 240                                        # default: 70
  titleCaseStyle = "Chicago"                                     # default: AP


####### LANGUAGE #######
  languageCode = "en-PH"
  defaultContentLanguage = "en-ph"                             # default: en
  hasCJKLanguage = true                                    # default: false
  disableLanguages = ["en", "fil", "tl-tglg", "zh-hant", "zh-hans"]


####### BACKEND #######
  #canonifyURLs = true                                      # default: false; marked for removeal; true for our use-case

  disableKinds = ["robotsTXT"]
  enableMissingTranslationPlaceholders = true              # default: false
  pluralizeListTitles = false                                # default: true
  #timeout = "30s"                                           # default: 30s

  #### Other settings ####
    disqusShortname = "youronlyone"                                    # .Site.DisqusShortname


#######  #######  #######  #######  #######  #######  #######  #######
