# See: https://gohugo.io/getting-started/configuration-markup

defaultMarkdownHandler = "goldmark"                               # default: goldmark

[asciidocExt]
  backend = "html5"                                               # default: html5
  extensions = []                                                 # default: []
  failureLevel = "fatal"                                          # default: fatal
  noHeaderOrFooter = true                                         # default: true
  preserveTOC = false                                             # default: false
  safeMode = "unsafe"                                             # default: unsafe
  sectionNumbers = false                                          # default: false
  trace = false                                                   # default: false
  verbose = false                                                 # default: false
  workingFolderCurrent = false                                    # default: false
  [asciidocExt.attributes]

[goldmark]
  [goldmark.extensions]
    definitionList = true                                         # default: true
    footnote = true                                               # default: true
    linkify = true                                                # default: true
    linkifyProtocol = 'https'                                     # default: true
    strikethrough = true                                          # default: true
    table = true                                                  # default: true
    taskList = true                                               # default: true
    typographer = true                                            # default: true
  [goldmark.parser]
    autoHeadingID = true                                          # default: true
    autoHeadingIDType = "github"                                  # default: github
    wrapStandAloneImageWithinParagraph = false                     # default: true
    [goldmark.parser.attribute]
      block = true                                               # default: false; keep true to use attributes in block type markdown
      title = true                                                # default: true
  [goldmark.renderer]
    hardWraps = false                                             # default: false
    unsafe = true                                                # default: false; keep true to use full HTML in markdown files
    xhtml = false                                                 # default: false

[highlight]
  anchorLineNos = false                                           # default: false
  codeFences = true                                               # default: true
  guessSyntax = true                                             # default: false
  hl_Lines = ""                                                   # default: ""
  hl_inline = false                                               # default: false
  lineAnchors = ""                                                # default: ""
  lineNoStart = 1                                                 # default: 1
  lineNos = true                                                 # default: false
  lineNumbersInTable = true                                       # default: true
  noClasses = false                                                # default: true
  noHl = false                                                    # default: false
  style = "monokai"                                               # default: monokai
  tabWidth = 4                                                    # default: 4

[tableOfContents]
  endLevel = 4                                                    # default: 3
  ordered = false                                                 # default: false
  startLevel = 2                                                  # default: 2

# This is new and undocumented. More options will become available. See Hugo github for details.
[pandoc]
  InputFormat = "markdown"                                        # default: markdown
  UseLegacyHtml = false                                           # default: false
  UseMathjax = true                                               # default: false
  #UseMathml = false                                               # default: false
  #UseWebtext = false                                              # default: false
  #UseKatex = true                                                 # default: true
  #[pandoc.filters]
  #[pandoc.extensions]
  #[pandoc.extraArgs]
