[[imports]]
  disable = false                           # default: false
  ignoreConfig = false                      # default: false
  ignoreImports = false                     # default: false
  noMounts = false                          # default: false
  noVendor = false                          # default: false
  path = "gitlab.com/youronlyone/defaults"

[[imports]]
  path = "gitlab.com/yelosan/hugo-semantic-web"

[[imports]]
  path = "gitlab.com/yelosan/hugo-shortcodes"

[[imports]]
  path = "gitlab.com/yelosan/hugo-feeds"

[[imports]]
  path = "github.com/techmagus/hugo-theme-future-imperfect-slim"

[[imports]]
  path = "gitlab.com/youronlyone/content"
  # BGN: /snoworld/ content
    #[[imports.mounts]]
    #  source = "snoworld/en-ph"
    #  target = "content"
    #  lang = "en"
    [[imports.mounts]]
      source = "snoworld/en-ph"
      target = "content"
      lang = "en-ph"
    [[imports.mounts]]
      source = "snoworld/ja"
      target = "content"
      lang = "ja"
    [[imports.mounts]]
      source = "snoworld/ko"
      target = "content"
      lang = "ko"
  # END: /snoworld/ content

  # BGN: /love/ content
    #[[imports.mounts]]
    #  source = "love/en-ph"
    #  target = "content"
    #  lang = "en"
    [[imports.mounts]]
      source = "love/en-ph"
      target = "content"
      lang = "en-ph"
      includeFiles = ["**/20160703-the-choice-2016.md"]
    [[imports.mounts]]
      source = "love/ja"
      target = "content"
      lang = "ja"
      includeFiles = ["**/20160703-the-choice-2016.md"]
    [[imports.mounts]]
      source = "love/ko"
      target = "content"
      lang = "ko"
      includeFiles = ["**/20160703-the-choice-2016.md"]
  # END: /love/ content

  # BGN: /snoworld/ fill gaps content
    [[imports.mounts]]
      source = "snoworld/en-ph"
      target = "content"
      lang = "ja"
    [[imports.mounts]]
      source = "snoworld/en-ph"
      target = "content"
      lang = "ko"
  # END: /snoworld/ fill gaps content


# See: https://gohugo.io/hugo-modules/configuration/#module-config-mounts
#   if you add a mounts section you should remove the old staticDir etc. settings.
#   When you add a mount, the default mount for the concerned target root is ignored: be sure to explicitly add it.
  [[mounts]]
    source = "archetypes"
    target = "archetypes"

  [[mounts]]
    source = "assets"
    target = "assets"

  #[[mounts]]
  #  source = "content/en-ph"
  #  target = "content"
  #  lang = "en"                                        # when in multihost / multilang mode
  [[mounts]]
    source = "content/en-ph"
    target = "content"
    lang = "en-ph"                                      # when in multihost / multilang mode
  [[mounts]]
    source = "content/ja"
    target = "content"
    lang = "ja"                                         # when in multihost / multilang mode
  [[mounts]]
    source = "content/ko"
    target = "content"
    lang = "ko"                                         # when in multihost / multilang mode

  [[mounts]]
    source = "data"
    target = "data"

  [[mounts]]
    source = "i18n"
    target = "i18n"

  [[mounts]]
    source = "layouts"
    target = "layouts"

  #[[mounts]]
  #  source = "static/en-ph"
  #  target = "static"
  #  lang = "en"                                        # when in multihost / multilang mode
  [[mounts]]
    source = "static/en-ph"
    target = "static"
    lang = "en-ph"                                      # when in multihost / multilang mode
  [[mounts]]
    source = "static/ja"
    target = "static"
    lang = "ja"                                         # when in multihost / multilang mode
  [[mounts]]
    source = "static/ko"
    target = "static"
    lang = "ko"                                         # when in multihost / multilang mode
