workspace = "off"

[[imports]]
  disable = false                           # default: false
  ignoreConfig = false                      # default: false
  ignoreImports = false                     # default: false
  noMounts = false                          # default: false
  noVendor = false                          # default: false
  path = "codeberg.org/yelosan/hugo-feeds"

[[imports]]
  path = "codeberg.org/yelosan/hugo-syndication"

[[imports]]
  path = "codeberg.org/yelosan/hugo-shortcodes"

[[imports]]
  path = "codeberg.org/yelosan/hugo-semantic-web"

[[imports]]
  ignoreConfig = true
  ignoreImports = true
  path = "gitlab.com/youronlyone/images"
  # BGN: /snoworld/ images
    [[imports.mounts]]
      source = "snoworld"
      target = "assets/images"
  # END: /snoworld/ images

  # BGN: /love/ images
    [[imports.mounts]]
      source = "love"
      target = "assets/images"
  # END: /love/ images

  # BGN: /yuki/ images
    [[imports.mounts]]
      source = "yuki"
      target = "assets/images"
  # END: /yuki/ images

[[imports]]
  ignoreConfig = true
  ignoreImports = true
  path = "codeberg.org/youronlyone/content"
  # BGN: /snoworld/ content
    [[imports.mounts]]
      source = "content/snoworld"
      target = "content"
      #lang = "en"
  # END: /snoworld/ content

  # BGN: /love/ content
    [[imports.mounts]]
      source = "content/love"
      target = "content"
      #lang = "en"
      includeFiles = ["**/channels/loverelationships/_index.*", "**/20160703-the-choice-2016.*"]
  # END: /love/ content

  # BGN: /yuki/ content
    [[imports.mounts]]
      source = "content/yuki"
      target = "content"
      #lang = "en"
      includeFiles = ["**/channels/faithfulathlete/_index.*", "**/channels/gameshogun/_index.*"]
  # END: /yuki/ content


  # BGN: /snoworld/ fill gaps content
    #[[imports.mounts]]
    #  source = "content/snoworld/en-ph"
    #  target = "content"
    #  lang = "ja"
    #[[imports.mounts]]
    #  source = "content/snoworld/en-ph"
    #  target = "content"
    #  lang = "ko"
  # END: /snoworld/ fill gaps content


[[imports]]
  path = "codeberg.org/yelosan/hugo-globals"

[[imports]]
  path = "codeberg.org/youronlyone/defaults"

[[imports]]
  ignoreConfig = true
  path = "github.com/techmagus/hugo-theme-future-imperfect-slim"


# See: https://gohugo.io/hugo-modules/configuration/#module-config-mounts
#   if you add a mounts section you should remove the old staticDir etc. settings.
#   When you add a mount, the default mount for the concerned target root is ignored: be sure to explicitly add it.
  [[mounts]]
    source = "archetypes"
    target = "archetypes"

  [[mounts]]
    source = "assets"
    target = "assets"

  [[mounts]]
    source = "content"
    target = "content"

  [[mounts]]
    source = "data"
    target = "data"

  [[mounts]]
    source = "i18n"
    target = "i18n"

  [[mounts]]
    source = "layouts"
    target = "layouts"

  [[mounts]]
    source = "static"
    target = "static"
