# home/atom.xml
home = ["HTML", "JSON", "Atom", "RSS"]                            # default: HTML, RSS

# home/section/PAGE-POST/atom.xml
page = ["HTML"]                            # default: HTML

# home/SECTION/atom.xml
section = ["HTML"]                         # default: HTML, RSS

# home/TAXONOMY/atom.xml
taxonomy = ["HTML"]                        # default: HTML, RSS

# home/taxonomy/TERM/atom.xml
term = ["HTML"]                            # default: HTML, RSS
