# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

#home = ["HTML", "JSON", "Atom", "RSS"]
page = ["HTML", "RSS"]
section = ["HTML", "Atom", "RSS"]
taxonomy = ["HTML", "Atom", "RSS"]
term = ["HTML", "Atom", "RSS"]
