# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

jquerycdn = true

favicon_mstilecolor = "#2d89ef"

### BGN: Structured Data ###
  siteStartYear = 2003
  description = "Society frozen and analysed"
  keywords = ["Snoworld", "스노우월드", "스노우 월드", "スノーワールド", "雪の世界", "YourOnlyOne", "YourOnly.One", "Yahuhanan Yukiya Sese Cuneta", "Yuki", "YoHan", "Yo-Han",  "יהוחנן", "ᜌᜓᜃᜒ", "사요한", "謝雪矢（ゆきや）", "스노", "Seu-No", "SeuNo", "Snow", "Yohanan", "ᜌᜓᜑᜈᜈ᜔", "ᜌᜓᜑᜈᜈ᜕", "ᜌᜑᜓᜑᜈᜈ᜔", "ᜌᜑᜓᜑᜈᜈ᜕"] # Can be overriden per page
  images = ["https://rsc.youronly.one/img/y/snoworld-square.webp", "https://rsc.youronly.one/img/y/snoworld-railroad-163518_1280.webp"]
### END: Structured Data ###

### BGN: Theme Settings ###
  enableCDN             = true
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "blog"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest"]
  hideEmptyStats        = true
  toc                   = true
  tocWords              = 400

  [meta]
    description         = "Society frozen and analysed"
    author              = "ᜌᜓᜃᜒ (Yuki ・ 雪亮)"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [header]
    navbarTitle         = "Snoworld"
    dynamicTitles       = false
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  [intro]
    header                = "Snoworld"
    paragraph             = "Society frozen and analysed"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [intro.pic]
      src                 = "https://rsc.youronly.one/img/y/snoworld-square.webp"
      shape               = "circle"
      width               = ""
      alt                 = "Snoworld"

  [sidebar]
    #about               = "ABOUT SIDEBAR"
    postAmount          = 10
    categories          = true
    categoriesByCount   = true
    tags                = true
    tagsByCount         = true
    series              = true
    seriesByCount       = true

  [footer]
    rssFooter           = true
    socialFooter        = true

  [utterances]
    enabled             = false
    #repo                = ""
    #issueTerm           = "pathname"
    #issueNumber         = ""
    #label               = ""
    #theme               = "github-light"

  [staticman]
    enabled             = false
    #api                 = ""  # No Trailing Slash
    #gitProvider         = ""
    #username            = ""
    #repo                = ""
    #branch              = ""

    #[staticman.recaptcha]
      #siteKey           = ""
      #encryptedKey      = ""
### END: Theme Settings ###

### BGN: Hugo module settings ###
  ##### BGN: syndication #####
    ## Custom entries only work if placed in per-site params.toml ##
    [[sns]]
      url = 'is.youronly.one'
      icon = 'bluesky.svg'
    [[sns]]
      url = 't.youronly.one'
      icon = 'tumblr.svg'

    ## Defaults
    [[sns]]
      url = 'blogspot.com'
      icon = 'blogspot.svg'
    [[sns]]
      url = 'bsky.app'
      icon = 'bluesky.svg'
    [[sns]]
      url = 'c.im'
      icon = 'mastodon.png'
    [[sns]]
      url = 'c.wtf'
      icon = 'rebased.svg'
    [[sns]]
      url = 'catodon.social'
      icon = 'catodon.png'
    [[sns]]
      url = 'coracle.social'
      icon = 'nostr.svg'
    [[sns]]
      url = 'diasp.org'
      icon = 'diaspora.svg'
    [[sns]]
      url = 'ebin.club'
      icon = 'fediverse.svg'
    [[sns]]
      url = 'facebook.com'
      icon = 'facebook.svg'
    [[sns]]
      url = 'fb.com'
      icon = 'facebook.svg'
    [[sns]]
      url = 'fedia.io'
      icon = 'mbin.svg'
    [[sns]]
      url = 'fedia.social'
      icon = 'iceshrimp.png'
    [[sns]]
      url = 'instagram.com'
      icon = 'instagram.svg'
    [[sns]]
      url = 'iris.to'
      icon = 'nostr.svg'
    [[sns]]
      url = 'mastodon.online'
      icon = 'mastodon.png'
    [[sns]]
      url = 'mastodon.social'
      icon = 'mastodon.png'
    [[sns]]
      url = 'naver.com'
      icon = 'naver.png'
    [[sns]]
      url = 'njump.me'
      icon = 'nostr.svg'
    [[sns]]
      url = 'nosta.me'
      icon = 'nostr.svg'
    [[sns]]
      url = 'p.lu'
      icon = 'peertube.svg'
    [[sns]]
      url = 'pixelfed.social'
      icon = 'pixelfed.svg'
    [[sns]]
      url = 'plurk.com'
      icon = 'plurk.svg'
    [[sns]]
      url = 'primal.net'
      icon = 'nostr.svg'
    [[sns]]
      url = 'reddit.com'
      icon = 'reddit.svg'
    [[sns]]
      url = 'satellite.earth'
      icon = 'nostr.svg'
    [[sns]]
      url = 'snort.social'
      icon = 'nostr.svg'
    [[sns]]
      url = 'socialhome.network'
      icon = 'socialhome-black.svg'
    [[sns]]
      url = 'spoutible.com'
      icon = 'spoutible.png'
    [[sns]]
      url = 'threads.net'
      icon = 'threads.svg'
    [[sns]]
      url = 'tumblr.com'
      icon = 'tumblr.svg'
    [[sns]]
      url = 'twitter.com'
      icon = 'twitter.svg'
    [[sns]]
      url = 'wordpress.com'
      icon = 'wordpress.svg'
    [[sns]]
      url = 'write.as'
      icon = 'writefreely.png'
    [[sns]]
      url = 'x.com'
      icon = 'x.svg'
    [[sns]]
      url = 'youtube.com'
      icon = 'youtube.svg'
  ##### END: syndication #####
### END: Hugo module settings ###

### BGN: Other Settings ###
  [semweb]
    datecreated = "2003-12-12"
    isblog = true
    sameas = [
      "https://www.facebook.com/snoworld",
      "https://c.im/@YourOnlyOne",
      "https://pixelfed.social/YourOnlyOne",
      "https://www.youtube.com/@YourOnlyOneOfcl",
      "https://www.facebook.com/YourOnly.ONE.ofcl"
    ]

  [tools]
    #onesignal = "79058a23-5e2c-4862-926f-37d20de118e5"
### END: Other Settings ###
