#mainSections = ["blog", "c"]

googleTagManager = "GTM-KT65GHZ"
subdir = "snoworld"
rssfull = "true"
faviconcache = "fmgy"
faviconbuster = "TimmieIsMyFate"
jquerycdn = true

### BGN: Structured Data ###
  siteStartYear = 2003
  description = "Society frozen and analysed."
  license = "https://im.youronly.one/p/legal-notice/"
  #issn = ""
  #awards = [""]
  images = ["https://rsc.youronly.one/img/y/snoworld-square.webp"]

  name = "YourOnly.One" # your company name
  primaryauthor = "ᜌᜓᜃᜒ (Yuki ・ 雪亮)" # Used as primary author if no specific is set
  ownerhomepage = "https://youronly.one"
  alternatenames = [ "JC John Sese Cuneta", "Yuki"]
  gender = "https://schema.org/Male"
  knowslanguages = ["en-PH", "fil", "tl-Tglg"]
  nationality = "Filipino"

  copyright = ""
  copyrightnotice = "JC John Sese Cuneta"
  copyrightyear = "2003"      # same as datePublished

  logourl = "https://rsc.youronly.one/img/y/snoworld-square.webp" # Used in structured data as logo url
  keywords = ["YourOnly.One", "Yuki", "ᜌᜓᜃᜒ", "Snoworld", "스노우 월드", "雪の世界"] # Can be overriden per page
  imageurl = "https://rsc.youronly.one/img/y/snoworld-square.webp" # Used in structured data as background image

  contact = "" # Primary email address
  phone = "" # Primary phone
  primarylocation = "" # Used as primary location if no specific is set

  color = "#000000"
  pricerange = "" # Used in structured data as price range
### END: Structured Data ###

### BGN: Theme Settings ###
  enableCDN             = true
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "posts"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest"]
  hideEmptyStats        = true

  [meta]
    description         = "Society frozen and analysed."
    author              = "ᜌᜓᜃᜒ (Yuki ・ 雪亮)"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [header]
    navbarTitle         = "Snoworld"
    dynamicTitles       = false
    searchMenu          = false
    shareMenu           = true
    languageMenu        = true

  [intro]
    header                = "Snoworld"
    paragraph             = "Society frozen and analysed"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [intro.pic]
      src                 = "https://rsc.youronly.one/img/y/snoworld-square.webp"
      shape               = "circle"
      width               = ""
      alt                 = "Snoworld"

  [sidebar]
    #about               = "ABOUT SIDEBAR"
    postAmount          = 10
    categories          = true
    categoriesByCount   = true
    tags                = true
    tagsByCount         = true
    series              = true
    seriesByCount       = true

  [footer]
    rssFooter           = true
    socialFooter        = true

  #[utterances]
    #enabled             = false
    #repo                = ""
    #issueTerm           = "pathname"
    #issueNumber         = ""
    #label               = ""
    #theme               = "github-light"

  #[staticman]
    #enabled             = true
    #api                 = ""  # No Trailing Slash
    #gitProvider         = ""
    #username            = ""
    #repo                = ""
    #branch              = ""

    #[staticman.recaptcha]
      #siteKey           = ""
      #encryptedKey      = ""
### END: Theme Settings ###

### BGN: Other Settings ###
  [author]                                                    # .Param "author.key"
    name = "ᜌᜓᜃᜒ (Yuki ・ 雪亮)"
    email = ""
    homepage = "https://youronly.one"
    avatar = "https://rsc.youronly.one/img/y/Yuki_flag-square-300x.webp"
    #emoji = "&#x1FAF0;&#x1F3FE;"
    emoji = "❄️"
    descriptionshort = "Born a writer and programmer."
    descriptionlong = "Lives in the Philippines and have been writing and programming at a young age."
    motto = "If this is not the end of oblivion, then I shall live everyday as if my life were to end on this very day."
    locationorigin = "Philippines"
    locationcurrent = "Philippines"
    organization = "Yelosan Publishing"

    rel = "me noopener"
    #rel = "noopener external nofollow"

  [siteowner]
    given_name = "Yahuhanan Yukia"
    middle_name = "Sese"
    family_name = "Cuneta"

  [semweb.publisher]
    name = "YourOnly.One"
    sameas = "https://youronly.one"

  [verify]
    naver = "0212955cb24d6e2c67f92be3c7833cae8a98fa8e"
    wot = "06c7ef6e7986586661ef"
### END: Other Settings ###
