# See: https://gohugo.io/content-management/related/#configure-related-content

includeNewer = true                       # "include pages newer than the current page"
threshold = 80
toLower = true                            # default: false; "lowercase keywords in both the indexes and the queries"

#[[indices]]
#  name = "name"
#  applyFilter = ""                        # currently only used for 'fragments' as of v0.111.x)
#  cardinalityThreshold = "0"              # default: 0; used to remove common keywords from the index
#  pattern = "2006"                        # default: 2006; or 200601 (year and month); only for dates
#  toLower = true                          # same as the global option above
#  type = "basic"                          # 'basic' or 'fragments'
#  weight = ""

#[[indices]]
#  name = "fragmentrefs"
#  type = "fragments"
#  applyFilter = false
#  weight = 60
#  cardinalityThreshold = 50

## Useful in hub/aggregate blogs
[[indices]]
  name = "channels"
  type = "basic"
  weight = 90

[[indices]]
  name = "categories"
  type = "basic"
  weight = 90

[[indices]]
  name = "date"
  pattern = "2006"
  type = "basic"
  weight = 10

## Using "keywords" is currently bugged.
##   see: https://github.com/gohugoio/hugo/issues/9188
#[[indices]]
#  name = "keywords"
#  type = "basic"
#  weight = 70

[[indices]]
  name = "lastmod"
  type = "basic"
  weight = 80

[[indices]]
  name = "series"
  type = "basic"
  weight = 100

[[indices]]
  name = "tags"
  type = "basic"
  weight = 100
